# Generated by Django 4.2.6 on 2023-10-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_kategoria_produkty_kategoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkty',
            new_name='Produkt',
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
