# Generated by Django 4.2.6 on 2023-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_rename_produkty_produkt_alter_kategoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default=None, upload_to='media/produkty/'),
        ),
    ]
