# Generated by Django 4.2.6 on 2023-10-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0008_alter_produkt_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='zdjecie',
        ),
    ]
