# Generated by Django 4.2.6 on 2023-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0009_remove_produkt_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/produkty/'),
        ),
    ]
